### PR TITLE
LIB001-1221: Adding previous and next arrows and styling on iconics reco...

### PR DESCRIPTION
**Pull request by ianthe**
...rd page

### CODE REVIEW

**Comment by ianthe** [comment]
This has been ignored and now won't merge automatically :(

**Comment by seesmith** [comment]
:( not good, was it waiting to be merged?

**Comment by ianthe** [comment]
Yeah, pull request I made 20 days ago. Don't worry, will sort it out tomorrow.

**Comment by ianthe** [comment]
BOOM! With a rebase!!! and git mergetool!

**Pull request merged**
